c $Id: units.inc,v 1.4 2005/06/02 10:51:39 hal Exp $
c
c     unit numbers
c

      integer stderr, uin, uout
      integer uwater, ustart, uinfo, uenout
      integer utraj, uveloc, uftraj
      integer ucoord, uqmen, uforce, upntch
      integer uumbst, uumbtr

      parameter (stderr = 0, uin = 5, uout = 6)
      parameter (uwater = 7, ustart = 8, uinfo = 9, uenout = 10)
      parameter (utraj = 11, uveloc = 12, uftraj = 13)
      parameter (ucoord = 14, uqmen = 15, uforce = 16, upntch = 17)
      parameter (uumbst = 18, uumbtr = 19)



c     Local Variables:
c     mode: fortran
c     End:
